services:
  aider-agent:
    build: .
    container_name: aider-agent
    volumes:
      - ./workspace:/workspace
      - .:/config
      - ~/.ssh:/root/.ssh:ro
    environment:
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      - MCP_CONFIG=/config/mcp-config/mcp.json
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MODEL=${MODEL:-anthropic/claude-3-sonnet}
      # Bitbucket MCP Configuration
      - BITBUCKET_USER=${BITBUCKET_USER}
      - BITBUCKET_APP_PASSWORD=${BITBUCKET_APP_PASSWORD}
      - BITBUCKET_WORKSPACE=${BITBUCKET_WORKSPACE}
      # Jira MCP Configuration
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_SERVER_URL=${JIRA_SERVER_URL}
    stdin_open: true
    tty: true
    command: aider --message "Welcome! I'm ready to help with your coding tasks. The ai-code-review repository has been cloned. Aider is enhanced with MCP clients for Bitbucket and Jira integration."
