services:
  bitbucket:
    image: atlassian/bitbucket:latest
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      BITBUCKET_SETUP_TOKEN: ${BITBUCKET_SETUP_TOKEN:-}
      BITBUCKET_SETUP_DISPLAYNAME: ${BITBUCKET_SETUP_DISPLAYNAME:-Bitbucket}
      BITBUCKET_SETUP_EMAIL: ${BITBUCKET_SETUP_EMAIL:-admin@example.com}
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7990/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  fast-agent:
    build: .
    container_name: fast-agent
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      
    volumes:
      # Optional: mount local config for customization
      - ./fastagent.config.yaml:/app/fastagent.config.yaml:ro

      # SSH keys for git operations (optional)
      - ~/.ssh:/tmp/.ssh:ro

      # Workspace volume for git operations (read-write)
      - ./workspaces:/app/workspaces:rw

    command: go --servers=bitbucket,bash

  gpt2giga:
    build:
      context: .
      dockerfile: Dockerfile.gpt2giga
    container_name: gpt2giga
    ports:
      - "8090:8090"
    restart: unless-stopped
    env_file:
      - ./.env

volumes:
  bitbucket-data:
